### ISSUE TITLE
blockstore: add an API to open either v1 or v2 as a read-only blockstore

### ISSUE THREAD

**Issue by mvdan** [ipld/go-car#128]

**Comment by raulk** [comment]
It’d be nice for blockstore.ReadOnlyOf to do the right thing regardless of whether the payload is a CARv1 or CARv2. Since it already requires a `ReaderAt`, it has the right access pattern to look at the header and decide. However, the edge case is what to do if the passed-in payload is an indexed CARv2. The passed-in index and the inline index could be different. I would expect the former to override the latter.

**Comment by mvdan** [comment]
Yup, that makes sense.

**Comment by masih** [comment]
`blockstore.ReaderOf` is now renamed to `blockstore.NewReadOnly`, with both `OpenReadOnly` and `NewReadOnly` accepting v1 and v2 payload generate index if it is not present.
