### ISSUE TITLE
v2: Open APIs should set io.Closer finalizers, like os.OpenFile

### ISSUE THREAD

**Issue by mvdan** [ipld/go-car#199]
This way, if someone encounters an error early, or otherwise forgets to close/finalize a CAR reader or blockstore, the underlying open file won't leak.

See https://pkg.go.dev/runtime#SetFinalizer.

cc @masih

**Comment by masih** [comment]
> like os.OpenFile

In which Go version is this performed?

**Comment by mvdan** [comment]
It has been done for many Go releases, I think. The logic is just hidden in the specific code for each platform: https://cs.opensource.google/search?q=setfinalizer%20filepath:src%2Fos%2Ffile&ss=go%2Fgo

The TL;DR is that, when opening a file, the finalizer is set on the "file" pointer to close itself when garbage collected. If the user closes the file before it's GCed, then the finalizer is set back to nil, to prevent closing it again.

**Comment by masih** [comment]
Thanks for the pointer @mvdan; that makes sense. 

I see we have three `Open*` APIs:
* `OpenReader` uses `mmap.Open` under the hood
* `blockstore.OpenReadOnly` also uses `mmap.Open` under the hood
* `blockstore.OpenReadWrite` uses `os.OpenFile`

Since `mmap.Open` handles finalisers already, that only leaves `blockstore.OpenReadWrite`. Unless I have missed something.

I'll put up a PR to get that sorted 🍻

**Comment by masih** [comment]
On closer look at the os-specific implementations of  `os.OpenFile` that does set finalisers too so I think we are good. Closing; please feel free to reopen if I have missed something 🙏
