### ISSUE TITLE
make carv2 SectionReaders gracefully reject operations after closure

### ISSUE THREAD

**Issue by raulk** [ipld/go-car#211]
Right now, if they receive a read after a closure, they panic. See https://github.com/filecoin-project/lotus/issues/7111.

We made the blockstores handle closures gracefully here: https://github.com/ipld/go-car/pull/195. We should do the same for standard car IO, so that these readers behave just like any other IO in Go (e.g. file IO, network IO, etc.)

**Comment by masih** [comment]
#212 asserts that reading from readers instantiated by `carv2.Reader` do not panic after the `Reader` is `Close`ed.

This leaves me to believe that if such panic occurs in lotus, bubbling up through a `carv2.Reader`, the `Reader` must have been instantiated using `carv2.NewReader` which takes an `io.ReaderAt`. In which case, the given `io.ReaderAt` must not be handling reads after closure gracefully; the fix for which would fall beyond the realms of go-car/v2. 

@raulk please shout if I have missed anything.

**Comment by raulk** [comment]
Thanks @masih for the quick turnaround. Closing this as the issue is related to NewReader with a supplied mmapped region.
